<?php
/**
 * Created by PhpStorm.
 * User: wanghaiyang
 * Date: 2018/10/17
 * Time: 9:37
 */
//信息采集
namespace app\admin\controller;

use think\Controller;

Class HttpdatacollectServerid extends Common {
    /**
     * 继承父类自动加载
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed|string
     * 渲染采集信息首页模块
     * 返回数据库表名 为服务器名
     * 返回默认数据
     */

    public function index()
    {
        $httpDataCollectServerModel = new \app\common\model\HttpdatacollectServerid();
        $result = $httpDataCollectServerModel->getTables();
        if($result['code'] == 0){
            $this->assign('tables',$result['data']);
            $this->assign('defaultTables',key($result['data']));
            return $this->fetch('index');
        }else{
            return '分库中暂无数据表';
        }

    }

    public function getHttpdatacollect()
    {
        $returnArray = array();
        $where = array();
        $errorModel = new \app\common\model\Error();

        if(isset($_GET["limit"])){
            $limit = $_GET["limit"];
        }else{
            $limit = 15;
        }
        if(isset($_GET["page"])){
            $offset = ($_GET["page"] -1) * $limit;
        }else{
            $offset = 0;
        }

        if(isset($_GET["tables_name"])){
            $tabaleName = $_GET["tables_name"];
        }else{
            $returnArray = array(
                'code' => 90002,
                'msg' => $errorModel::ERRORCODE[90002],
                'data' => array()
            );
        }

        if(empty($returnArray)){
            $httpDataCollectServerModel = new \app\common\model\HttpdatacollectServerid();
            $result = $httpDataCollectServerModel->getList($tabaleName,$offset,$limit) ;
        }
        if($result) {
            return $result;
        }
    }

    /**
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * 导出数据CSV
     */

    public function exportCsv()
    {
        $head = array('序号','服务器ID','HOST','URL','用户ip地址','请求ip地址','来源地址','UA','时间戳');
        $httpDataCollectServerModel = new \app\common\model\HttpdatacollectServerid();
        $result = $httpDataCollectServerModel->exportCsv($_GET['table_name'],'test.csv',$_GET['table_name'],$head);
        return $result;
    }


    public function delTable()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_GET['table_name'])){
            $httpDataCollectServerModel = new \app\common\model\HttpdatacollectServerid();
            $result = $httpDataCollectServerModel->delTable($_GET['table_name']);
            if($result){
                return $result;
            }
        }else{
            $returnArray = array(
                'code' => 90002,
                'msg' => $errorModel::ERRORCODE[90002],
                'data' => array()
            );
            return $returnArray;
        }
    }

}