<?php
/**
 * Created by PhpStorm.
 * User: wanghaiyang
 * Date: 2018/11/23
 * Time: 10:07
 */
namespace app\admin\controller;

use app\common\model\Operationlog;
use think\Controller;
use think\Request;

Class Prohibitpush extends Common{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Request
     */
    public function index()
    {
        $serverDataModel = new \app\common\model\Serverdata();
//        获取服务器列表
        $result = $serverDataModel->getServerList('',0,1000,0);
        if($result['code'] == 0){
            $this->assign('serverList',$result['data']);
            $this->assign('serverDefault',$result['data'][0]['id']);
            return $this->fetch('index');
        }

    }


    /**
     * @return array获取绑定列表
     *
     */
    public function getProhibitpushList()
    {
        if(isset($_GET["limit"])){
            $limit = $_GET["limit"];
        }else{
            $limit = 15;
        }
        if(isset($_GET["page"])){
            $offset = ($_GET["page"] -1) * $limit;
        }else{
            $offset = 0;
        }
        if(isset($_GET["serverid"])){
            $serverid = $_GET["serverid"];
        }else{
            $serverid = 0;
        }

        if(isset($_GET["content"])){
            $content = $_GET["content"];
        }else{
            $content = '';
        }

        $ProhibitpushModel = new \app\common\model\Prohibitpush();
        $result = $ProhibitpushModel->getList($offset,$limit,$serverid,$content);
//        var_dump($result);
        return $result;
    }

    /**渲染添加页面
     * @return mixed
     */
    public function add()
    {
        if(!empty($_GET['serverid'])){
            $this->assign('serverid',$_GET['serverid']);
            return $this->fetch('prohibit_to_push/add');
        }

    }

    /**添加动作action
     * @return array
     * @param data 数组
     */
    public function addAction()
    {
        if(!empty($_POST['data']) && is_array($_POST['data'])){
            $ProhibitpushModel = new \app\common\model\Prohibitpush();
            $result = $ProhibitpushModel->addAction($_POST['data']);
            if($result){
                Operationlog::addOperation($this->userId,Request::instance()->module(),Request::instance()->controller(),Request::instance()->action(),1,'[禁止推送]在服务器id：'.$_POST['data']['serverid'].'下添加：'.$_POST['data']['content']);
                return $result;
            }
        }
    }


    public function edit()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_GET['serverid']) &&!empty($_GET['id'])  ){
            $ProhibitpushModel = new \app\common\model\Prohibitpush();
            $result = $ProhibitpushModel->getListONe(array('id' => $_GET['id']));
            if($result['code'] == 0){
                $this->assign('prohibitDetails',$result['data'][0]);
                return $this->fetch('prohibit_to_push/edit');
            }else{

            }

        }else{
            $returnArray = array(
                'code' => 10005,
                'msg' => $errorModel::ERRORCODE[10005],
                'data' => array()
            );

            return $returnArray;
        }

    }

    /**
     * @return array修改action
     * data要修改的数组
     */
    public function editAction()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_POST['data']) && is_array($_POST['data']) && !empty($_POST['data']['id'])){
            $ProhibitpushModel = new \app\common\model\Prohibitpush();
            $where = array();
            $where['id'] = $_POST['data']['id'];
            $result = $ProhibitpushModel->upDateRecode($where,$_POST['data']);
            if($result){
                return $result;
            }
        }else{
            $returnArray = array(
                'code' => 10005,
                'msg' => $errorModel::ERRORCODE[10005],
                'data' => array()
            );
            return $returnArray;
        }
    }

    /**
     * 删除操作
     */
    public function delAction()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_POST['id'])){
            $ProhibitpushModel = new \app\common\model\Prohibitpush();
            $result = $ProhibitpushModel->delRecode(array('id'=>$_POST['id']));
            if($result){
                Operationlog::addOperation($this->userId,Request::instance()->module(),Request::instance()->controller(),Request::instance()->action(),3,'[禁止推送]删除ID：'.$_POST['id'].'，内容：'.$_POST['content']);
                return $result;
            }
        }else{
             $returnArray = array(
                 'code' => 10005,
                 'msg' => $errorModel::ERRORCODE[10005],
                 'data' => array()
             );

            return $returnArray;
        }
    }
}