<?php
/**
 * Created by PhpStorm.
 * User: wanghaiyang
 * Date: 2018/10/19
 * Time: 11:43
 */
namespace app\admin\controller;

use think\Controller;

Class Pushpolicy extends Common{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch('index');
    }

    /**
     * 获取列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */

    public function getPushpolicyList()
    {
        if(isset($_GET["limit"])){
            $limit = $_GET["limit"];
        }else{
            $limit = 15;
        }
        if(isset($_GET["page"])){
            $offset = ($_GET["page"] -1) * $limit;
        }else{
            $offset = 0;
        }


        if(isset($_GET["name"])){
            $name = $_GET["name"];
        }else{
            $name = '';
        }


        $pushpolicyModel = new \app\common\model\Pushpolicy();
        $result = $pushpolicyModel->getList($offset,$limit,$name);
//        var_dump($result);
        return $result;
    }




    /**渲染添加页面
     * @return mixed
     */
    public function add()
    {
        return $this->fetch('add');

    }

    /**添加动作action
     * @return array
     * @param data 数组
     */
    public function addAction()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_POST['data']) && is_array($_POST['data'])){
            if($_POST['data']['time'] < 1){
                $returnArray = array(
                    'code' => 11006,
                    'msg' => $errorModel::ERRORCODE[11006],
                    'data' => array()
                );
            }
            if($_POST['data']['seq'] < 1){
                $returnArray = array(
                    'code' => 11007,
                    'msg' => $errorModel::ERRORCODE[11007],
                    'data' => array()
                );
            }

            if(empty($returnArray)){
                $pushpolicyModel = new \app\common\model\Pushpolicy();
                $result = $pushpolicyModel->addAction($_POST['data']);
                if($result){
                    return $result;
                }
            }else{
                return $returnArray;
            }

        }
    }


    public function edit()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_GET['id'])  ){
            $pushpolicyModel = new \app\common\model\Pushpolicy();
            $result = $pushpolicyModel->getListONe(array('id' => $_GET['id']));
            if($result['code'] == 0){
                $this->assign('pushpolicy',$result['data'][0]);
                return $this->fetch('edit');
            }else{

            }

        }else{
            $returnArray = array(
                'code' => 10005,
                'msg' => $errorModel::ERRORCODE[10005],
                'data' => array()
            );

            return $returnArray;
        }

    }

    /**
     * @return array修改action
     * data要修改的数组
     */
    public function editAction()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_POST['data']) && is_array($_POST['data']) && !empty($_POST['data']['id'])){

            if($_POST['data']['time'] < 1){
                $returnArray = array(
                    'code' => 11006,
                    'msg' => $errorModel::ERRORCODE[11006],
                    'data' => array()
                );
            }
            if($_POST['data']['seq'] < 1){
                $returnArray = array(
                    'code' => 11007,
                    'msg' => $errorModel::ERRORCODE[11007],
                    'data' => array()
                );
            }
            if(empty($returnArray)){
                $pushpolicyModel = new \app\common\model\Pushpolicy();
                $where = array();
                $where['id'] = $_POST['data']['id'];
                $result = $pushpolicyModel->upDateRecode($where,$_POST['data']);
                if($result){
                    return $result;
                }
            }else{
                return $returnArray;
            }
        }else{
            $returnArray = array(
                'code' => 10005,
                'msg' => $errorModel::ERRORCODE[10005],
                'data' => array()
            );
            return $returnArray;
        }
    }

    /**
     * 删除操作
     */
    public function delAction()
    {
        $returnArray = array();
        $errorModel = new \app\common\model\Error();
        if(!empty($_POST['id'])){
            $pushpolicyModel = new \app\common\model\Pushpolicy();
            $result = $pushpolicyModel->delRecode(array('id'=>$_POST['id'],'seq'=>$_POST['seq']));
            if($result){
                return $result;
            }
        }else{
            $returnArray = array(
                'code' => 10005,
                'msg' => $errorModel::ERRORCODE[10005],
                'data' => array()
            );

            return $returnArray;
        }
    }
}