<?php
/**
 * Created by PhpStorm.
 * User: wanghaiyang
 * Explain: 服务器统计控制器
 * Date: 2018/10/16
 * Time: 14:25
 */
namespace app\admin\controller;

use think\Controller;

Class Serverstatistics extends Common{
    /**
     * 继承父类，验证登陆及其权限
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 流量渲染
     */
    public function flow()
    {

        if(!empty($_GET['serverid'])){
            $serverDataModel = new \app\common\model\Serverdata();
            $result = $serverDataModel->getServerOne($_GET['serverid']);
            $this->assign('server',$result['data'][0]);
            $this->assign('serverid',$_GET['serverid']);
            return $this->fetch('flow');
        }
    }

    /**
     * 获取服务器列表统计内容
     */

    public function getServerstatistics()
    {
        $errorModel = new \app\common\model\Error();

        if(isset($_GET["limit"])){
            $limit = $_GET["limit"];
        }else{
            $limit = 15;
        }
        if(isset($_GET["startTime"])){
            $startTime = $_GET["startTime"];
        }else{
            $startTime = 0;
        }
        if(isset($_GET["endTime"])){
            $endTime = $_GET["endTime"];
        }else{
            $endTime = 0;
        }
        if(isset($_GET["page"])){
            $offset = ($_GET["page"] -1) * $limit;
        }else{
            $offset = 0;
        }

        if(!empty($_GET['serverid'])){
            $serverStatisticsModel = new \app\common\model\Serverstatistics();
            $where = array();
            $where['serverid'] = $_GET['serverid'];
            $result = $serverStatisticsModel->getList($where,$offset,$limit,$startTime,$endTime);
        }else{
            $result = array(
                'code' => 10002,
                'msg' => $errorModel::ERRORCODE[10002],
                'data' => array()
            );
        }
        return $result;
    }
}